// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROYJHOME2026.Data;

#nullable disable

namespace PROYJHOME2026.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414134845_V11_FueEditadoInspecciones")]
    partial class V11_FueEditadoInspecciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROYJHOME2026.Models.Asesorio", b =>
                {
                    b.Property<int>("IdAsesorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsesorio"));

                    b.Property<string>("TipoAsesorio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAsesorio");

                    b.ToTable("Asesorios");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Asignacion", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<string>("CorreoEquipo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EstadoAsignacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdChip")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int?>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdChip");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdGrupo");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.AuditoriaLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEntidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("IpCliente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdLog");

                    b.ToTable("AuditoriaLog");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Carro", b =>
                {
                    b.Property<int>("IdCarro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarro"));

                    b.Property<decimal?>("CargaUtil")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Ejes")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCarro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroMotor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdCarro");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroAsesorio", b =>
                {
                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int>("IdAsesorio")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignada")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaVencimientoExtintor")
                        .HasColumnType("date");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PesoExtintor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoExtintor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdCarro", "IdAsesorio");

                    b.HasIndex("IdAsesorio");

                    b.ToTable("Carro_Asesorio");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroConductorLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpleadoAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpleadoNuevo")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreConductorAnterior")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreConductorNuevo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdLog");

                    b.HasIndex("IdCarro");

                    b.ToTable("CarroConductorLog");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroEstadoLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdLog");

                    b.HasIndex("IdCarro");

                    b.ToTable("CarroEstadoLog");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroModalidad", b =>
                {
                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int>("IdModalidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCarro", "IdModalidad");

                    b.HasIndex("IdModalidad");

                    b.ToTable("Carro_Modalidad");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroModalidadLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Accion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int>("IdModalidad")
                        .HasColumnType("int");

                    b.Property<string>("TipoModalidad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdLog");

                    b.HasIndex("IdCarro");

                    b.ToTable("CarroModalidadLog");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroSeguro", b =>
                {
                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int>("IdSeguro")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCulminada")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCarro", "IdSeguro");

                    b.HasIndex("IdSeguro");

                    b.ToTable("Carro_Seguro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CheckListTransporte", b =>
                {
                    b.Property<int>("IdCheckList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCheckList"));

                    b.Property<DateOnly>("FechaInspeccion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FueEditado")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("HoraInspeccion")
                        .HasColumnType("time");

                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreResponsable")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ObservacionesGenerales")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SedeArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCheckList");

                    b.HasIndex("IdCarro");

                    b.ToTable("CheckListTransporte");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CheckListTransporteItem", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<bool?>("Cumple")
                        .HasColumnType("bit");

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdCheckList")
                        .HasColumnType("int");

                    b.Property<string>("NombreSeccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Seccion")
                        .HasColumnType("int");

                    b.HasKey("IdItem");

                    b.HasIndex("IdCheckList");

                    b.ToTable("CheckListTransporteItem");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Chip", b =>
                {
                    b.Property<int>("IdChip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChip"));

                    b.Property<string>("NumeroCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdChip");

                    b.ToTable("Chips");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Empleado", b =>
                {
                    b.Property<int>("idEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEmpleado"));

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("materno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paterno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEmpleado");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoCarro", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleado", "IdCarro");

                    b.HasIndex("IdCarro");

                    b.ToTable("Empleados_Carros");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoEstadoLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdLog");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("EmpleadoEstadoLog");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoGrupo", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleado", "IdGrupo");

                    b.HasIndex("IdGrupo");

                    b.ToTable("Empleado_Grupo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoSeguro", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdSeguro")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCulminada")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEmpleado", "IdSeguro");

                    b.HasIndex("IdSeguro");

                    b.ToTable("Empleado_Seguro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Equipo", b =>
                {
                    b.Property<int>("idEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEquipo"));

                    b.Property<string>("Disco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("EsInalambrico")
                        .HasColumnType("bit");

                    b.Property<string>("FuenteEnergia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("GraficosIntegrados")
                        .HasColumnType("bit");

                    b.Property<string>("IMEI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombrePc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PcCpuDisco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PcCpuFuenteEnergia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("PcCpuGraficosIntegrados")
                        .HasColumnType("bit");

                    b.Property<string>("PcCpuMarca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcCpuModelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcCpuProcesador")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PcCpuRam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcCpuSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcCpuSistemaOperativo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcCpuTarjetaGrafica")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PcCpuTarjetaMadre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PcCpuVersionSO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcMonitorMarca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcMonitorModelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcMonitorSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("PcMouseEsInalambrico")
                        .HasColumnType("bit");

                    b.Property<string>("PcMouseMarca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcMouseModelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcMouseSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcMousepadMarca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcTecladoMarca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcTecladoModelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcTecladoSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Procesador")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TarjetaGrafica")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TarjetaMadre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("estado_equipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_compra")
                        .HasColumnType("datetime2");

                    b.Property<int>("idTipoEquipo")
                        .HasColumnType("int");

                    b.Property<string>("marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("numero_serie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("sistema_operativo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idEquipo");

                    b.HasIndex("idTipoEquipo");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EquipoComponenteLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Componente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdLog");

                    b.HasIndex("IdEquipo");

                    b.ToTable("EquipoComponenteLogs");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Grupo", b =>
                {
                    b.Property<int>("idGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idGrupo"));

                    b.Property<string>("area")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idGrupo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.GrupoAsesorio", b =>
                {
                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdAsesorio")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignada")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaVencimientoExtintor")
                        .HasColumnType("date");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PesoExtintor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoExtintor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdGrupo", "IdAsesorio");

                    b.HasIndex("IdAsesorio");

                    b.ToTable("Grupo_Asesorio");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Historial", b =>
                {
                    b.Property<int>("IdHistoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistoria"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAsignacion")
                        .HasColumnType("int");

                    b.Property<int>("IdMotivo")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdHistoria");

                    b.HasIndex("IdAsignacion");

                    b.HasIndex("IdMotivo");

                    b.ToTable("Historiales");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionBotiquinGrupo", b =>
                {
                    b.Property<int>("IdInspeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInspeccion"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("FechaInspeccion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FueEditado")
                        .HasColumnType("bit");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("InspeccionadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("InstaladoEnPared")
                        .HasColumnType("bit");

                    b.Property<bool>("LibreDeObstaculos")
                        .HasColumnType("bit");

                    b.Property<bool>("LocalizadoVisible")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroBotiquin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Piso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Senalizado")
                        .HasColumnType("bit");

                    b.HasKey("IdInspeccion");

                    b.HasIndex("IdGrupo");

                    b.ToTable("InspeccionBotiquinGrupo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionBotiquinGrupoItem", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdInspeccion")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("SeEncuentra")
                        .HasColumnType("bit");

                    b.HasKey("IdItem");

                    b.HasIndex("IdInspeccion");

                    b.ToTable("InspeccionBotiquinGrupoItem");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionBotiquinTransporte", b =>
                {
                    b.Property<int>("IdInspeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInspeccion"));

                    b.Property<DateOnly>("FechaInspeccion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FueEditado")
                        .HasColumnType("bit");

                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("InspeccionadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LibreDeObstaculos")
                        .HasColumnType("bit");

                    b.Property<bool>("LocalizadoVisible")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroBotiquin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Senalizado")
                        .HasColumnType("bit");

                    b.Property<bool>("UbicadoEnSuLugar")
                        .HasColumnType("bit");

                    b.HasKey("IdInspeccion");

                    b.HasIndex("IdCarro");

                    b.ToTable("InspeccionBotiquinTransporte");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionBotiquinTransporteItem", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdInspeccion")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("SeEncuentra")
                        .HasColumnType("bit");

                    b.HasKey("IdItem");

                    b.HasIndex("IdInspeccion");

                    b.ToTable("InspeccionBotiquinTransporteItem");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionExtintor", b =>
                {
                    b.Property<int>("IdInspeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInspeccion"));

                    b.Property<DateOnly>("FechaInspeccion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FueEditado")
                        .HasColumnType("bit");

                    b.Property<int>("IdAsesorio")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("InspeccionadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdInspeccion");

                    b.HasIndex("IdAsesorio");

                    b.ToTable("InspeccionExtintor");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionExtintorFila", b =>
                {
                    b.Property<int>("IdFila")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFila"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdInspeccion")
                        .HasColumnType("int");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacion18")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ObservacionesMarcadas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PesoExtintor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoExtintor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdFila");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdInspeccion");

                    b.ToTable("InspeccionExtintorFila");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.MantenimientoCarro", b =>
                {
                    b.Property<int>("IdMante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMante"));

                    b.Property<string>("ComentarioCulminacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCulminada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoMante")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdMante");

                    b.HasIndex("IdCarro");

                    b.HasIndex("IdTipoMante");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Mantenimiento_carro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Maquina", b =>
                {
                    b.Property<int>("IdMaquina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaquina"));

                    b.Property<string>("AccesoriosParte")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreMaquina")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroMaquina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdMaquina");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.MaquinaAsignacion", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<bool>("EsActiva")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoOperativo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleadoEncargado")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdMaquina")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdEmpleadoEncargado");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdMaquina")
                        .IsUnique();

                    b.ToTable("MaquinaAsignaciones");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.MaquinaLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMaquina")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdLog");

                    b.HasIndex("IdMaquina");

                    b.ToTable("MaquinaLogs");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Modalidad", b =>
                {
                    b.Property<int>("IdModalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModalidad"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaVigente")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoModalidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdModalidad");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Motivo", b =>
                {
                    b.Property<int>("IdMotivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMotivo"));

                    b.Property<string>("TipoMotivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMotivo");

                    b.ToTable("Motivos");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdMante")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Seguro", b =>
                {
                    b.Property<int>("IdSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeguro"));

                    b.Property<string>("TipoSeguro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSeguro");

                    b.ToTable("Seguro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.TipoEquipo", b =>
                {
                    b.Property<int>("idTipoEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoEquipo"));

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTipoEquipo");

                    b.ToTable("TiposEquipo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.TipoMantenimiento", b =>
                {
                    b.Property<int>("IdTipoMante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMante"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoMante");

                    b.ToTable("TipoMantenimiento");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("bloqueadoHasta")
                        .HasColumnType("datetime2");

                    b.Property<string>("correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("creadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("intentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("nombreCompleto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("numeroCelular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ultimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idUsuario");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Asignacion", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Chip", "Chip")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdChip")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PROYJHOME2026.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Equipo", "Equipo")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chip");

                    b.Navigation("Empleado");

                    b.Navigation("Equipo");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroAsesorio", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Asesorio", "Asesorio")
                        .WithMany("CarroAsesorios")
                        .HasForeignKey("IdAsesorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany("CarroAsesorios")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asesorio");

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroConductorLog", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroEstadoLog", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroModalidad", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany("CarroModalidades")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Modalidad", "Modalidad")
                        .WithMany("CarroModalidades")
                        .HasForeignKey("IdModalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Modalidad");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroModalidadLog", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroSeguro", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany("CarroSeguros")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Seguro", "Seguro")
                        .WithMany("CarroSeguros")
                        .HasForeignKey("IdSeguro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CheckListTransporte", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CheckListTransporteItem", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.CheckListTransporte", "CheckList")
                        .WithMany("Items")
                        .HasForeignKey("IdCheckList")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckList");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoCarro", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany("EmpleadosCarros")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoEstadoLog", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoGrupo", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoSeguro", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Seguro", "Seguro")
                        .WithMany("EmpleadoSeguros")
                        .HasForeignKey("IdSeguro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Equipo", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.TipoEquipo", "TipoEquipo")
                        .WithMany()
                        .HasForeignKey("idTipoEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EquipoComponenteLog", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Equipo", "Equipo")
                        .WithMany("ComponenteLogs")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.GrupoAsesorio", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Asesorio", "Asesorio")
                        .WithMany("GrupoAsesorios")
                        .HasForeignKey("IdAsesorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asesorio");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Historial", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Asignacion", "Asignacion")
                        .WithMany("Historiales")
                        .HasForeignKey("IdAsignacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Motivo", "Motivo")
                        .WithMany("Historiales")
                        .HasForeignKey("IdMotivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("Motivo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionBotiquinGrupo", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionBotiquinGrupoItem", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.InspeccionBotiquinGrupo", "Inspeccion")
                        .WithMany("Items")
                        .HasForeignKey("IdInspeccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspeccion");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionBotiquinTransporte", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionBotiquinTransporteItem", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.InspeccionBotiquinTransporte", "Inspeccion")
                        .WithMany("Items")
                        .HasForeignKey("IdInspeccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspeccion");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionExtintor", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Asesorio", "Asesorio")
                        .WithMany()
                        .HasForeignKey("IdAsesorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asesorio");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionExtintorFila", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.InspeccionExtintor", "Inspeccion")
                        .WithMany("Filas")
                        .HasForeignKey("IdInspeccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Inspeccion");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.MantenimientoCarro", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany("MantenimientosCarros")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("MantenimientosCarros")
                        .HasForeignKey("IdTipoMante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Carro");

                    b.Navigation("TipoMantenimiento");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.MaquinaAsignacion", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Empleado", "Encargado")
                        .WithMany()
                        .HasForeignKey("IdEmpleadoEncargado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Maquina", "Maquina")
                        .WithOne("AsignacionActual")
                        .HasForeignKey("PROYJHOME2026.Models.MaquinaAsignacion", "IdMaquina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encargado");

                    b.Navigation("Grupo");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.MaquinaLog", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Maquina", "Maquina")
                        .WithMany("Logs")
                        .HasForeignKey("IdMaquina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Notificacion", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Asesorio", b =>
                {
                    b.Navigation("CarroAsesorios");

                    b.Navigation("GrupoAsesorios");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Asignacion", b =>
                {
                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Carro", b =>
                {
                    b.Navigation("CarroAsesorios");

                    b.Navigation("CarroModalidades");

                    b.Navigation("CarroSeguros");

                    b.Navigation("EmpleadosCarros");

                    b.Navigation("MantenimientosCarros");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CheckListTransporte", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Chip", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Equipo", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("ComponenteLogs");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionBotiquinGrupo", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionBotiquinTransporte", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.InspeccionExtintor", b =>
                {
                    b.Navigation("Filas");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Maquina", b =>
                {
                    b.Navigation("AsignacionActual");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Modalidad", b =>
                {
                    b.Navigation("CarroModalidades");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Motivo", b =>
                {
                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Seguro", b =>
                {
                    b.Navigation("CarroSeguros");

                    b.Navigation("EmpleadoSeguros");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.TipoMantenimiento", b =>
                {
                    b.Navigation("MantenimientosCarros");
                });
#pragma warning restore 612, 618
        }
    }
}
