// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROYJHOME2026.Data;

#nullable disable

namespace PROYJHOME2026.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310172306_AgregarNuevosModelos")]
    partial class AgregarNuevosModelos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROYJHOME2026.Models.Asesorio", b =>
                {
                    b.Property<int>("IdAsesorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsesorio"));

                    b.Property<string>("TipoAsesorio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAsesorio");

                    b.ToTable("Asesorios");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Asignacion", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<string>("EstadoAsignacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdChip")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdChip");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEquipo");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Carro", b =>
                {
                    b.Property<int>("IdCarro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarro"));

                    b.Property<decimal?>("CargaUtil")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Ejes")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCarro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroMotor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdCarro");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroAsesorio", b =>
                {
                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int>("IdAsesorio")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdCarro", "IdAsesorio");

                    b.HasIndex("IdAsesorio");

                    b.ToTable("Carro_Asesorio");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroModalidad", b =>
                {
                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int>("IdModalidad")
                        .HasColumnType("int");

                    b.HasKey("IdCarro", "IdModalidad");

                    b.HasIndex("IdModalidad");

                    b.ToTable("Carro_Modalidad");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroSeguro", b =>
                {
                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int>("IdSeguro")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCulminada")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCarro", "IdSeguro");

                    b.HasIndex("IdSeguro");

                    b.ToTable("Carro_Seguro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Chip", b =>
                {
                    b.Property<int>("IdChip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChip"));

                    b.Property<string>("NumeroCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdChip");

                    b.ToTable("Chips");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Empleado", b =>
                {
                    b.Property<int>("idEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEmpleado"));

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("materno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paterno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEmpleado");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoCarro", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleado", "IdCarro");

                    b.HasIndex("IdCarro");

                    b.ToTable("Empleados_Carros");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoGrupo", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleado", "IdGrupo");

                    b.HasIndex("IdGrupo");

                    b.ToTable("Empleado_Grupo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoSeguro", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdSeguro")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCulminada")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEmpleado", "IdSeguro");

                    b.HasIndex("IdSeguro");

                    b.ToTable("Empleado_Seguro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Equipo", b =>
                {
                    b.Property<int>("idEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEquipo"));

                    b.Property<string>("correo_equipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado_equipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_compra")
                        .HasColumnType("datetime2");

                    b.Property<int>("idTipoEquipo")
                        .HasColumnType("int");

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero_serie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sistema_operativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEquipo");

                    b.HasIndex("idTipoEquipo");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Grupo", b =>
                {
                    b.Property<int>("idGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idGrupo"));

                    b.Property<string>("area")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idGrupo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.GrupoAsesorio", b =>
                {
                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdAsesorio")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdGrupo", "IdAsesorio");

                    b.HasIndex("IdAsesorio");

                    b.ToTable("Grupo_Asesorio");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Historial", b =>
                {
                    b.Property<int>("IdHistoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistoria"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAsignacion")
                        .HasColumnType("int");

                    b.Property<int>("IdMotivo")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdHistoria");

                    b.HasIndex("IdAsignacion");

                    b.HasIndex("IdMotivo");

                    b.ToTable("Historiales");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.MantenimientoCarro", b =>
                {
                    b.Property<int>("IdMante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMante"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCulminada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaMante")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCarro")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoMante")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdMante");

                    b.HasIndex("IdCarro");

                    b.HasIndex("IdTipoMante");

                    b.ToTable("Mantenimiento_carro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Modalidad", b =>
                {
                    b.Property<int>("IdModalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModalidad"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaVigente")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoModalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdModalidad");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Motivo", b =>
                {
                    b.Property<int>("IdMotivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMotivo"));

                    b.Property<string>("TipoMotivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMotivo");

                    b.ToTable("Motivos");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Seguro", b =>
                {
                    b.Property<int>("IdSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeguro"));

                    b.Property<string>("TipoSeguro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSeguro");

                    b.ToTable("Seguro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.TipoEquipo", b =>
                {
                    b.Property<int>("idTipoEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoEquipo"));

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTipoEquipo");

                    b.ToTable("TiposEquipo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.TipoMantenimiento", b =>
                {
                    b.Property<int>("IdTipoMante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMante"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoMante");

                    b.ToTable("TipoMantenimiento");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Asignacion", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Chip", "Chip")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdChip")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PROYJHOME2026.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chip");

                    b.Navigation("Empleado");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroAsesorio", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Asesorio", "Asesorio")
                        .WithMany("CarroAsesorios")
                        .HasForeignKey("IdAsesorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany("CarroAsesorios")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asesorio");

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroModalidad", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany("CarroModalidades")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Modalidad", "Modalidad")
                        .WithMany("CarroModalidades")
                        .HasForeignKey("IdModalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Modalidad");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.CarroSeguro", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany("CarroSeguros")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Seguro", "Seguro")
                        .WithMany("CarroSeguros")
                        .HasForeignKey("IdSeguro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoCarro", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany("EmpleadosCarros")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoGrupo", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.EmpleadoSeguro", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Seguro", "Seguro")
                        .WithMany("EmpleadoSeguros")
                        .HasForeignKey("IdSeguro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Equipo", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.TipoEquipo", "TipoEquipo")
                        .WithMany()
                        .HasForeignKey("idTipoEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.GrupoAsesorio", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Asesorio", "Asesorio")
                        .WithMany("GrupoAsesorios")
                        .HasForeignKey("IdAsesorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asesorio");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Historial", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Asignacion", "Asignacion")
                        .WithMany("Historiales")
                        .HasForeignKey("IdAsignacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.Motivo", "Motivo")
                        .WithMany("Historiales")
                        .HasForeignKey("IdMotivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("Motivo");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.MantenimientoCarro", b =>
                {
                    b.HasOne("PROYJHOME2026.Models.Carro", "Carro")
                        .WithMany("MantenimientosCarros")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYJHOME2026.Models.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("MantenimientosCarros")
                        .HasForeignKey("IdTipoMante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("TipoMantenimiento");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Asesorio", b =>
                {
                    b.Navigation("CarroAsesorios");

                    b.Navigation("GrupoAsesorios");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Asignacion", b =>
                {
                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Carro", b =>
                {
                    b.Navigation("CarroAsesorios");

                    b.Navigation("CarroModalidades");

                    b.Navigation("CarroSeguros");

                    b.Navigation("EmpleadosCarros");

                    b.Navigation("MantenimientosCarros");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Chip", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Modalidad", b =>
                {
                    b.Navigation("CarroModalidades");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Motivo", b =>
                {
                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.Seguro", b =>
                {
                    b.Navigation("CarroSeguros");

                    b.Navigation("EmpleadoSeguros");
                });

            modelBuilder.Entity("PROYJHOME2026.Models.TipoMantenimiento", b =>
                {
                    b.Navigation("MantenimientosCarros");
                });
#pragma warning restore 612, 618
        }
    }
}
